version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "javascript"
    versioning-strategy: "increase"
