version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    commit-message:
      prefix: "chore(client)"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/server"
    commit-message:
      prefix: "chore(server)"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
    versioning-strategy: "increase"
